/*******************************************************************************
    CANopen Object Dictionary definition for CANopenNode V4

    This file was automatically generated by CANopenEditor da8409a-dirty+da8409a60d4fcb997a85ffd2c672744b7f600cec

    https://github.com/CANopenNode/CANopenNode
    https://github.com/CANopenNode/CANopenEditor

    DON'T EDIT THIS FILE MANUALLY !!!!
********************************************************************************

    File info:
        File Names:   OD.h; OD.c
        Project File: CANbp.xdd
        File Version: 1

        Created:      08.03.2026 13:12:11
        Created By:   
        Modified:     09.03.2026 20:17:47
        Modified By:  

    Device Info:
        Vendor Name:  
        Vendor ID:    
        Product Name: SDO-BOOT
        Product ID:   0

        Description:  
*******************************************************************************/

#ifndef OD_H
#define OD_H
/*******************************************************************************
    Counters of OD objects
*******************************************************************************/
#define OD_CNT_NMT 1
#define OD_CNT_EM 1
#define OD_CNT_HB_PROD 1
#define OD_CNT_SDO_SRV 1


/*******************************************************************************
    Sizes of OD arrays
*******************************************************************************/


/*******************************************************************************
    OD data declaration of all groups
*******************************************************************************/
typedef struct {
    uint32_t x1000_deviceType;
    uint8_t x1001_errorRegister;
    uint16_t x1017_producerHeartbeatTime;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t vendorID;
        uint32_t productCode;
        uint32_t revisionNumber;
        uint32_t serialNumber;
    } x1018_identity;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t COB_IDClientToServerRx;
        uint32_t COB_IDServerToClientTx;
    } x1200_SDOServerParameter;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t command;
        uint8_t target;
        uint8_t imageType;
        uint32_t sessionId;
        uint32_t expectedSize;
        uint32_t expectedCRC32;
        uint16_t chunkSize;
        uint16_t imageAddress;
    } x5F00_fwUpdateControl;
    struct {
        uint8_t highestSub_indexSupported;
        uint8_t state;
        uint16_t lastError;
        uint32_t bytesReceived;
        uint32_t bytesWritten;
        uint32_t imageCRC32;
        uint8_t progress;
    } x5F01_fwUpdateStatus;
    struct {
        uint8_t highestSub_indexSupported;
        uint32_t mainFwVersion;
        uint32_t commFwVersion;
        uint32_t userFwVersion;
        uint32_t ODVersion;
        uint32_t bootFwVersion;
    } x5F03_fwUpdateInfo;
} OD_RAM_t;

#ifndef OD_ATTR_RAM
#define OD_ATTR_RAM
#endif
extern OD_ATTR_RAM OD_RAM_t OD_RAM;

#ifndef OD_ATTR_OD
#define OD_ATTR_OD
#endif
extern OD_ATTR_OD OD_t *OD;


/*******************************************************************************
    Object dictionary entries - shortcuts
*******************************************************************************/
#define OD_ENTRY_H1000 &OD->list[0]
#define OD_ENTRY_H1001 &OD->list[1]
#define OD_ENTRY_H1008 &OD->list[2]
#define OD_ENTRY_H100A &OD->list[3]
#define OD_ENTRY_H1017 &OD->list[4]
#define OD_ENTRY_H1018 &OD->list[5]
#define OD_ENTRY_H1200 &OD->list[6]
#define OD_ENTRY_H5F00 &OD->list[7]
#define OD_ENTRY_H5F01 &OD->list[8]
#define OD_ENTRY_H5F02 &OD->list[9]
#define OD_ENTRY_H5F03 &OD->list[10]


/*******************************************************************************
    Object dictionary entries - shortcuts with names
*******************************************************************************/
#define OD_ENTRY_H1000_deviceType &OD->list[0]
#define OD_ENTRY_H1001_errorRegister &OD->list[1]
#define OD_ENTRY_H1008_manufacturerDeviceName &OD->list[2]
#define OD_ENTRY_H100A_manufacturerSoftwareVersion &OD->list[3]
#define OD_ENTRY_H1017_producerHeartbeatTime &OD->list[4]
#define OD_ENTRY_H1018_identity &OD->list[5]
#define OD_ENTRY_H1200_SDOServerParameter &OD->list[6]
#define OD_ENTRY_H5F00_fwUpdateControl &OD->list[7]
#define OD_ENTRY_H5F01_fwUpdateStatus &OD->list[8]
#define OD_ENTRY_H5F02_fwUpdateData &OD->list[9]
#define OD_ENTRY_H5F03_fwUpdateInfo &OD->list[10]


/*******************************************************************************
    OD config structure
*******************************************************************************/
#ifdef CO_MULTIPLE_OD
#define OD_INIT_CONFIG(config) {\
    (config).CNT_NMT = OD_CNT_NMT;\
    (config).ENTRY_H1017 = OD_ENTRY_H1017;\
    (config).CNT_HB_CONS = 0;\
    (config).CNT_ARR_1016 = 0;\
    (config).ENTRY_H1016 = NULL;\
    (config).CNT_EM = OD_CNT_EM;\
    (config).ENTRY_H1001 = OD_ENTRY_H1001;\
    (config).ENTRY_H1014 = NULL;\
    (config).ENTRY_H1015 = NULL;\
    (config).CNT_ARR_1003 = 0;\
    (config).ENTRY_H1003 = NULL;\
    (config).CNT_SDO_SRV = OD_CNT_SDO_SRV;\
    (config).ENTRY_H1200 = OD_ENTRY_H1200;\
    (config).CNT_SDO_CLI = 0;\
    (config).ENTRY_H1280 = NULL;\
    (config).CNT_TIME = 0;\
    (config).ENTRY_H1012 = NULL;\
    (config).CNT_SYNC = 0;\
    (config).ENTRY_H1005 = NULL;\
    (config).ENTRY_H1006 = NULL;\
    (config).ENTRY_H1007 = NULL;\
    (config).ENTRY_H1019 = NULL;\
    (config).CNT_RPDO = 0;\
    (config).ENTRY_H1400 = NULL;\
    (config).ENTRY_H1600 = NULL;\
    (config).CNT_TPDO = 0;\
    (config).ENTRY_H1800 = NULL;\
    (config).ENTRY_H1A00 = NULL;\
    (config).CNT_LEDS = 0;\
    (config).CNT_GFC = 0;\
    (config).ENTRY_H1300 = NULL;\
    (config).CNT_SRDO = 0;\
    (config).ENTRY_H1301 = NULL;\
    (config).ENTRY_H1381 = NULL;\
    (config).ENTRY_H13FE = NULL;\
    (config).ENTRY_H13FF = NULL;\
    (config).CNT_LSS_SLV = 0;\
    (config).CNT_LSS_MST = 0;\
    (config).CNT_GTWA = 0;\
    (config).CNT_TRACE = 0;\
}
#endif

#endif /* OD_H */
